elasticsearch: fix fetch_points()
The new unit test would have caused:
```
======================================================================
ERROR: test_fetch_points_updates_read_on (__main__.TestAccessorWithElasticsearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/drivers/test_elasticsearch.py", line 361, in test_fetch_points_updates_read_on
    points = self.accessor.fetch_points(metric, 0, 1, metric.retention[0])
  File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/elasticsearch.py", line 651, in fetch_points
    self.__update_read_on_on_need(metric)
  File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/elasticsearch.py", line 735, in __update_read_on_on_need
    read_on_timestamp = ttls.str_to_timestamp(metric.read_on)
  File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/ttls.py", line 43, in str_to_timestamp
    datetime_tuple = str_to_datetime(str_repr)
  File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/ttls.py", line 36, in str_to_datetime
    return dateutil.parser.parse(str_repr)
  File "/home/cchary/dev/graphite/biggraphite/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/cchary/dev/graphite/biggraphite/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 645, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/cchary/dev/graphite/biggraphite/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 721, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/cchary/dev/graphite/biggraphite/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/cchary/dev/graphite/biggraphite/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not datetime
```

Also:
* Make TestAccessorWithElasticsearch inherit directly from
  BaseTestAccessorMetadata. This makes more sense because we
  use self.assert* inside it.
* Change ttls.str_from_datetime() to allow datetimes as arguments.