elasticsearch: ignore missing documents in touch_metric()
Without the fix, the test raises the following error:
```
======================================================================
ERROR: test_touch_without_create (__main__.TestAccessorWithElasticsearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cchary/dev/graphite/biggraphite/tests/drivers/base_test_metadata.py", line 373, in test_touch_without_create
    self.accessor.touch_metric(metric)
  File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/elasticsearch.py", line 661, in touch_metric
    if not document.updated_on:
AttributeError: 'NoneType' object has no attribute 'updated_on'
```